"""
Django settings for AGT project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Import du fichier de constantes personnalisées pour l'application :
from .constants import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0@ea3lnf52^(dhv4h)r*12ub3&-cxzy0ddln^a@w^z3_-cw*qd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CORE.apps.CoreConfig',
    'AD_A2P.apps.AdA2PConfig',
    'AD_AGT.apps.AdAgtConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AGT.urls'

TEMPLATES = [
    # Configuration pour le moteur Jinja2 :
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        # Répertoire pour les templates Jinja2 :
        'DIRS': [
            BASE_DIR / 'jinja2_templates',
            BASE_DIR / 'CORE' / 'jinja2_templates',
            BASE_DIR / 'AD_A2P' / 'jinja2_templates',
            BASE_DIR / 'AD_AGT' / 'jinja2_templates',
        ]
        ,
        'APP_DIRS': True,                      # Désactivation de la recherche automatique pour les templates Jinja2
        'OPTIONS': {
            'environment': 'AGT.jinja2.environment',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'AGT.context_processors.global_settings',
                'AGT.context_processors.csrf_token_processor',
                'AGT.context_processors.media_url_processor',
                'AGT.context_processors.previous_url',
            ],
        },
    },

    # Configuration pour le moteur DjangoTemplates :
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Répertoire pour les templates Django
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'AGT.context_processors.global_settings',
                'AGT.context_processors.csrf_token_processor',
                'AGT.context_processors.media_url_processor',
                'AGT.context_processors.previous_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'AGT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Ajout de la liste de définition des fichiers statiques :
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Ajout du dossier media :
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Ajout de SITE_URL (utile pour Jinja2) :
if DEBUG:
    SITE_URL = 'http://localhost:8000'
else:
    SITE_URL = 'https://votresite.com'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
