# Generated by Django 5.1.5 on 2025-01-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('qr_code_generation', models.BooleanField(default=False, verbose_name='QR Code généré')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('matched_photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du fichier photo')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
