# Generated by Django 5.1.5 on 2025-02-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
