# Generated by Django 5.1.5 on 2025-02-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0003_photo_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='fk_id_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CORE.student', verbose_name='Elève associé'),
        ),
    ]
