# Generated by Django 5.1.5 on 2025-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0004_photo_fk_id_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='crop_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='crop_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='crop_width',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='crop_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='crop_y',
            field=models.FloatField(default=0),
        ),
    ]
