# Generated by Django 5.1.5 on 2025-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0005_photo_crop_height_photo_crop_lock_photo_crop_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cropped',
            field=models.BooleanField(default=False),
        ),
    ]
